# See dvae_pytorch/training/dvae/config.py for more information about
# specific options.
model:
  codebook_size: 2048
  codebook_vector_dim: 256
  hidden_dim: 128
  channels: 1
  num_layers: 1
  num_resnet_blocks: 3
training:
  train_variable: 'toa_incident_solar_radiation'
  learning_rate: 5e-4
  lr_decay_rate: 0.98
  kl_div_weight_scheduler:
    start: 0
    end: 0
    warmup: 0.1
    cooldown: 0.2
  temperature_scheduler:
    start: 0.3
    min:  1e-2
    anneal_rate: 1e-6
  batch_size: 256
  max_epochs: 40
  gradient_clip_val: 0.5
  save_vis_every_n_step: 100