# See dvae_pytorch/training/dvae/config.py for more information about
# specific options.
model:
  num_heads: 25
  n_encoder_layers: 6
  n_decoder_layers: 6
  dropout: 0.1
training:
  learning_rate: 2e-5
  warmup_step: 3000
  batch_size: 4
  max_epochs: 20  
  gradient_clip_val: 0.5  
  tgt_time_len: 24
  train_offset: 0
  train_variable:
    - geopotential
    - specific_humidity
    - temperature
    - u_component_of_wind
    - v_component_of_wind
    - vertical_velocity
    - 2m_temperature
    - 10m_u_component_of_wind
    - 