# See dvae_pytorch/training/dvae/config.py for more information about
# specific options.
model:
  num_heads:10
  n_encoder_layers: 3
  n_decoder_layers: 3
  dropout: 0.1
training:
  learning_rate: 1e-3
  lr_decay_rate: 0.98
  kl_div_weight_scheduler:
    start: 0
    end: 0
    warmup: 0.1
    cooldown: 0.2
  temperature_scheduler:
    start: 0.3
    min:  1e-2
    anneal_rate: 1e-6
  batch_size: 16
  max_epochs: 50
  gradient_clip_val: 0.5
  save_vis_every_n_step: 200