# See dvae_pytorch/training/dvae/config.py for more information about
# specific options.
model:
  num_heads: 10
  n_encoder_layers: 3
  n_decoder_layers: 3
  dropout: 0.1
training:
  learning_rate: 1e-3
  warmup_step: 4000
  max_iters: 7000
  batch_size: 256
  max_epochs: 20
  gradient_clip_val: 0.5