# See dvae_pytorch/training/dvae/config.py for more information about
# specific options.
model:
  num_heads: 10
  n_encoder_layers: 4
  n_decoder_layers: 2
  dropout: 0.1
training:
  learning_rate: 1e-4
  warmup_step: 100
  batch_size: 8
  max_epochs: 20
  gradient_clip_val: 0.5
  log_every_n_step: 100
  log_batch: 2