wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708086876.908808
    t:
      1:
      - 1
      - 9
      - 41
      - 51
      - 54
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 41
      - 51
      - 54
      - 55
      - 103
      - 105
      3:
      - 7
      - 13
      - 23
      4: 3.10.13
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-AdamW
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: temperature
      5: 1
      6:
      - 1
    - 1: kl_div_weight
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val/predictions._type
      5: 1
      6:
      - 1
    - 1: val/predictions.width
      5: 1
      6:
      - 1
    - 1: val/predictions.height
      5: 1
      6:
      - 1
    - 1: val/predictions.format
      5: 1
      6:
      - 1
    - 1: val/predictions.count
      5: 1
      6:
      - 1
    - 1: val/predictions.filenames
      5: 1
      6:
      - 1
    - 1: val/codebook_indices._type
      5: 1
      6:
      - 1
    - 1: val/codebook_indices.values
      5: 1
      6:
      - 1
    - 1: val/codebook_indices.bins
      5: 1
      6:
      - 1
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: test/loss
      5: 1
      6:
      - 1
train_variable:
  desc: null
  value: geopotential
learning_rate:
  desc: null
  value: 0.0005
lr_decay_rate:
  desc: null
  value: 0.98
kl_div_weight_scheduler:
  desc: null
  value:
    start: 0.0
    end: 0.0
    warmup: 0.1
    cooldown: 0.2
temperature_scheduler:
  desc: null
  value:
    start: 0.2
    min: 0.01
    anneal_rate: 1.0e-06
batch_size:
  desc: null
  value: 256
max_epochs:
  desc: null
  value: 40
gradient_clip_val:
  desc: null
  value: 0.5
save_vis_every_n_step:
  desc: null
  value: 300
num_vis:
  desc: null
  value: 10
