# See dvae_pytorch/training/dvae/config.py for more information about
# specific options.
model:
  num_heads: 20
  n_layers: 12
  dropout: 0.1
training:
  learning_rate: 2e-5
  warmup_step: 3000
  batch_size: 16
  max_epochs: 20
  gradient_clip_val: 0.5
  lead_time: 4
  train_offset: 0
  air_variable:
    - geopotential
    - specific_humidity
    - temperature
    - u_component_of_wind
    - v_component_of_wind
    - vertical_velocity
  surface_variable:
    - 2m_temperature
    - 10m_u_component_of_wind
    - 10m_v_component_of_wind
    - mean_sea_level_pressure
    - total_cloud_cover
    - total_precipitation